-- AlterTable
ALTER TABLE "Camper"
ADD COLUMN "dateOfBirth" TEXT NOT NULL DEFAULT '',
ADD COLUMN "gender" TEXT NOT NULL DEFAULT '',
ADD COLUMN "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN "parentsName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "telephoneNumberOfParents" TEXT NOT NULL DEFAULT '',
ADD COLUMN "religion" TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "Camper" ALTER COLUMN "dateOfBirth" DROP DEFAULT,
ALTER COLUMN "gender" DROP DEFAULT,
ALTER COLUMN "address" DROP DEFAULT,
ALTER COLUMN "parentsName" DROP DEFAULT,
ALTER COLUMN "telephoneNumberOfParents" DROP DEFAULT,
ALTER COLUMN "religion" DROP DEFAULT;